# Generated by Django 5.2.12 on 2026-05-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('educator', 'Educator'), ('interpreter', 'Interpreter')], default='learner', max_length=20)),
                ('bio', models.TextField(blank=True, default='', max_length=300)),
                ('avatar_initial', models.CharField(blank=True, default='', max_length=2)),
                ('date_joined_display', models.DateTimeField(auto_now_add=True)),
                ('total_signs_practiced', models.PositiveIntegerField(default=0)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('total_translations', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
